# Generated by Django 5.0.6 on 2024-07-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-modified', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-modified', '-created']},
        ),
    ]
