# Generated by Django 5.0.6 on 2024-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
